# Generated by Django 4.2.6 on 2023-12-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('ename', models.CharField(max_length=100)),
                ('empno', models.PositiveIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('dept_name', models.CharField(max_length=100)),
                ('dept_no', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('dept_loc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('ename', models.CharField(max_length=100)),
                ('empno', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('job', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Salgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveIntegerField()),
            ],
        ),
    ]
